// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `event` module.
///
/// Player event definitions, dispatching and subscriptions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/event/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/event/event_context.dart';
export 'package:media_core/event/event_dispatcher.dart';
export 'package:media_core/event/event_filter.dart';
export 'package:media_core/event/event_priority.dart';
export 'package:media_core/event/event_subscription.dart';
export 'package:media_core/event/player_event.dart';
export 'package:media_core/event/player_event_bus.dart';
export 'package:media_core/event/player_event_type.dart';
