// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `lifecycle` module.
///
/// Player, page and application lifecycle management..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/lifecycle/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'lifecycle_controller.dart';
export 'lifecycle_event.dart';
export 'lifecycle_observer.dart';
export 'lifecycle_snapshot.dart';
export 'lifecycle_state.dart';
export 'player_lifecycle.dart';
