// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `platform` module.
///
/// Platform capabilities and platform-specific abstractions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/platform/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'platform_audio.dart';
export 'platform_capabilities.dart';
export 'platform_info.dart';
export 'platform_lifecycle.dart';
export 'platform_network.dart';
export 'platform_pip.dart';
export 'platform_provider.dart';
export 'platform_renderer.dart';
export 'platform_surface.dart';
export 'platform_type.dart';
