// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `platform` module.
///
/// Platform capabilities and platform-specific abstractions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/platform/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/platform/platform_audio.dart';
export 'package:media_core/platform/platform_capabilities.dart';
export 'package:media_core/platform/platform_info.dart';
export 'package:media_core/platform/platform_lifecycle.dart';
export 'package:media_core/platform/platform_network.dart';
export 'package:media_core/platform/platform_codec_capabilities.dart';
export 'package:media_core/platform/platform_device_profile.dart';
export 'package:media_core/platform/platform_pip.dart';
export 'package:media_core/platform/platform_provider.dart';
export 'package:media_core/platform/platform_renderer.dart';
export 'package:media_core/platform/platform_surface.dart';
export 'package:media_core/platform/platform_type.dart';
