// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `screenshot` module.
///
/// Frame capture for a player: engine capture, rendered-surface capture, the
/// captured-frame value and file writing..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/screenshot/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/screenshot/player_screenshot.dart';
export 'package:media_core/screenshot/screenshot_config.dart';
export 'package:media_core/screenshot/screenshot_format.dart';
export 'package:media_core/screenshot/screenshot_manager.dart';
export 'package:media_core/screenshot/screenshot_options.dart';
export 'package:media_core/screenshot/screenshot_request.dart';
export 'package:media_core/screenshot/screenshot_surface.dart';
export 'package:media_core/screenshot/screenshot_writer.dart';
