// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `quality` module.
///
/// Quality candidates and live switching continuity: the unit a
/// viewer chooses from, and the sequence that moves a playing handle
/// between encodings of the same media without losing the
/// position..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/quality/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/quality/quality_candidate.dart';
export 'package:media_core/quality/quality_switch_controller.dart';
