// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `testing` module.
///
/// Internal test doubles and testing infrastructure..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/testing/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/testing/fake_clock.dart';
export 'package:media_core/testing/fake_lifecycle.dart';
export 'package:media_core/testing/fake_network.dart';
export 'package:media_core/testing/fake_platform.dart';
export 'package:media_core/testing/fake_player.dart';
export 'package:media_core/testing/fake_player_adapter.dart';
export 'package:media_core/testing/fake_timer.dart';
export 'package:media_core/testing/fake_visibility.dart';
export 'package:media_core/testing/test_assertions.dart';
export 'package:media_core/testing/test_player_factory.dart';
export 'package:media_core/testing/test_scenarios.dart';
export 'package:media_core/testing/test_session_factory.dart';
export 'package:media_core/testing/test_source_factory.dart';
