// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `testing` module.
///
/// Internal test doubles and testing infrastructure..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/testing/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'fake_clock.dart';
export 'fake_lifecycle.dart';
export 'fake_network.dart';
export 'fake_platform.dart';
export 'fake_player.dart';
export 'fake_player_adapter.dart';
export 'fake_timer.dart';
export 'fake_visibility.dart';
export 'test_assertions.dart';
export 'test_player_factory.dart';
export 'test_scenarios.dart';
export 'test_session_factory.dart';
export 'test_source_factory.dart';
