// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `fallback` module.
///
/// Backend, line and quality fallback mechanisms..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/fallback/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/fallback/backend_fallback.dart';
export 'package:media_core/fallback/backend_fallback_state.dart';
export 'package:media_core/fallback/fallback_context.dart';
export 'package:media_core/fallback/fallback_manager.dart';
export 'package:media_core/fallback/fallback_reason.dart';
export 'package:media_core/fallback/fallback_result.dart';
export 'package:media_core/fallback/line_fallback.dart';
export 'package:media_core/fallback/line_fallback_state.dart';
export 'package:media_core/fallback/quality_fallback.dart';
export 'package:media_core/fallback/quality_fallback_state.dart';
