// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `fallback` module.
///
/// Backend, line and quality fallback mechanisms..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/fallback/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'backend_fallback.dart';
export 'backend_fallback_state.dart';
export 'fallback_context.dart';
export 'fallback_manager.dart';
export 'fallback_reason.dart';
export 'fallback_result.dart';
export 'line_fallback.dart';
export 'line_fallback_state.dart';
export 'quality_fallback.dart';
export 'quality_fallback_state.dart';
