// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `geometry` module.
///
/// Video geometry, orientation, rotation and display dimensions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/geometry/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/geometry/aspect_ratio.dart';
export 'package:media_core/geometry/display_size.dart';
export 'package:media_core/geometry/geometry_controller.dart';
export 'package:media_core/geometry/geometry_event.dart';
export 'package:media_core/geometry/geometry_session.dart';
export 'package:media_core/geometry/geometry_snapshot.dart';
export 'package:media_core/geometry/geometry_state.dart';
export 'package:media_core/geometry/pixel_ratio.dart';
export 'package:media_core/geometry/video_geometry.dart';
export 'package:media_core/geometry/video_orientation.dart';
export 'package:media_core/geometry/video_rotation.dart';
export 'package:media_core/geometry/video_size.dart';
