// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `geometry` module.
///
/// Video geometry, orientation, rotation and display dimensions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/geometry/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'aspect_ratio.dart';
export 'display_size.dart';
export 'geometry_controller.dart';
export 'geometry_event.dart';
export 'geometry_session.dart';
export 'geometry_snapshot.dart';
export 'geometry_state.dart';
export 'pixel_ratio.dart';
export 'video_geometry.dart';
export 'video_orientation.dart';
export 'video_rotation.dart';
export 'video_size.dart';
