// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `state_machine` module.
///
/// Generic state-machine infrastructure and state transitions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/state_machine/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'state.dart';
export 'state_machine.dart';
export 'state_machine_context.dart';
export 'state_machine_controller.dart';
export 'state_machine_event.dart';
export 'state_transition.dart';
export 'state_transition_result.dart';
