// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `remux` module.
///
/// Playback services: the media remuxer contract that folds composite
/// essence streams into a single playable source..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/remux/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/remux/media_remuxer.dart';
