// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `presentation` module.
///
/// Fullscreen, picture-in-picture and floating presentation..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/presentation/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'floating_controller.dart';
export 'floating_state.dart';
export 'fullscreen_controller.dart';
export 'fullscreen_state.dart';
export 'pip_controller.dart';
export 'pip_state.dart';
export 'presentation.dart';
export 'presentation_adapter.dart';
export 'presentation_adapter_base.dart';
export 'presentation_capabilities.dart';
export 'presentation_controller.dart';
export 'presentation_dispatcher.dart';
export 'presentation_event.dart';
export 'presentation_manager.dart';
export 'presentation_mode.dart';
export 'presentation_reducer.dart';
export 'presentation_request.dart';
export 'presentation_service.dart';
export 'presentation_snapshot.dart';
export 'presentation_state.dart';
