// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `presentation` module.
///
/// Fullscreen, picture-in-picture and floating presentation..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/presentation/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/presentation/floating_controller.dart';
export 'package:media_core/presentation/floating_state.dart';
export 'package:media_core/presentation/fullscreen_controller.dart';
export 'package:media_core/presentation/fullscreen_fit_strategy.dart';
export 'package:media_core/presentation/fullscreen_state.dart';
export 'package:media_core/presentation/pip_controller.dart';
export 'package:media_core/presentation/pip_state.dart';
export 'package:media_core/presentation/presentation.dart';
export 'package:media_core/presentation/presentation_adapter.dart';
export 'package:media_core/presentation/presentation_adapter_base.dart';
export 'package:media_core/presentation/presentation_capabilities.dart';
export 'package:media_core/presentation/presentation_controller.dart';
export 'package:media_core/presentation/presentation_dispatcher.dart';
export 'package:media_core/presentation/presentation_driver_chain.dart';
export 'package:media_core/presentation/presentation_event.dart';
export 'package:media_core/presentation/presentation_lifecycle.dart';
export 'package:media_core/presentation/presentation_manager.dart';
export 'package:media_core/presentation/presentation_mode.dart';
export 'package:media_core/presentation/presentation_reducer.dart';
export 'package:media_core/presentation/presentation_request.dart';
export 'package:media_core/presentation/presentation_service.dart';
export 'package:media_core/presentation/presentation_snapshot.dart';
export 'package:media_core/presentation/presentation_state.dart';
