// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `slot` module.
///
/// Logical player slot ownership, assignment and state..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/slot/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/slot/player_slot.dart';
export 'package:media_core/slot/player_slot_assignment.dart';
export 'package:media_core/slot/player_slot_manager.dart';
export 'package:media_core/slot/player_slot_owner.dart';
export 'package:media_core/slot/player_slot_snapshot.dart';
export 'package:media_core/slot/player_slot_state.dart';
export 'package:media_core/slot/player_slot_status.dart';
