// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `visibility` module.
///
/// Player visibility observation, state and management..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/visibility/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/visibility/visibility_controller.dart';
export 'package:media_core/visibility/visibility_event.dart';
export 'package:media_core/visibility/visibility_metrics.dart';
export 'package:media_core/visibility/player_visibility_binding.dart';
export 'package:media_core/visibility/visibility_observer.dart';
export 'package:media_core/visibility/visibility_snapshot.dart';
export 'package:media_core/visibility/visibility_state.dart';
