// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `visibility` module.
///
/// Player visibility observation, state and management..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/visibility/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'visibility_controller.dart';
export 'visibility_event.dart';
export 'visibility_metrics.dart';
export 'visibility_observer.dart';
export 'visibility_snapshot.dart';
export 'visibility_state.dart';
