// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `resource` module.
///
/// Decoder, memory, bandwidth and thermal resource management..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/resource/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/resource/bandwidth_budget.dart';
export 'package:media_core/resource/bandwidth_manager.dart';
export 'package:media_core/resource/decoder_budget.dart';
export 'package:media_core/resource/decoder_manager.dart';
export 'package:media_core/resource/memory_pressure_bridge.dart';
export 'package:media_core/resource/resource_manager.dart';
export 'package:media_core/resource/resource_metrics.dart';
export 'package:media_core/resource/resource_pressure.dart';
export 'package:media_core/resource/resource_priority.dart';
export 'package:media_core/resource/resource_snapshot.dart';
export 'package:media_core/resource/resource_state.dart';
export 'package:media_core/resource/thermal_manager.dart';
export 'package:media_core/resource/thermal_state.dart';

// Memory accounting lives in its own package and is re-exported here so the
// resource layer keeps one import surface.
export 'package:media_core_memory/media_core_memory.dart';
