// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `resource` module.
///
/// Decoder, memory, bandwidth and thermal resource management..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/resource/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'bandwidth_budget.dart';
export 'bandwidth_manager.dart';
export 'decoder_budget.dart';
export 'decoder_manager.dart';
export 'memory_budget.dart';
export 'memory_manager.dart';
export 'resource_manager.dart';
export 'resource_metrics.dart';
export 'resource_pressure.dart';
export 'resource_priority.dart';
export 'resource_snapshot.dart';
export 'resource_state.dart';
export 'thermal_manager.dart';
export 'thermal_state.dart';
