// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `factory` module.
///
/// Player and backend factory, registration and selection..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/factory/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'default_player_factory.dart';
export 'player_factory.dart';
export 'player_factory_config.dart';
