// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `factory` module.
///
/// Player and backend factory, registration and selection..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/factory/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'backend_capabilities.dart';
export 'backend_descriptor.dart';
export 'backend_factory.dart';
export 'backend_instance.dart';
export 'backend_registry.dart';
export 'backend_selection_request.dart';
export 'backend_selection_result.dart';
export 'backend_selector.dart';
export 'player_factory.dart';
export 'player_factory_config.dart';
