// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `concurrency` module.
///
/// Mutex, semaphore, locking and concurrency control primitives..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/concurrency/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/concurrency/concurrency_key.dart';
export 'package:media_core/concurrency/concurrency_limit.dart';
export 'package:media_core/concurrency/concurrency_manager.dart';
export 'package:media_core/concurrency/exclusive_task.dart';
export 'package:media_core/concurrency/lock.dart';
export 'package:media_core/concurrency/mutex.dart';
export 'package:media_core/concurrency/semaphore.dart';
export 'package:media_core/concurrency/serial_executor.dart';
