// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `concurrency` module.
///
/// Mutex, semaphore, locking and concurrency control primitives..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/concurrency/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'concurrency_key.dart';
export 'concurrency_limit.dart';
export 'concurrency_manager.dart';
export 'exclusive_task.dart';
export 'lock.dart';
export 'mutex.dart';
export 'semaphore.dart';
export 'serial_executor.dart';
