// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `adapter` module.
///
/// Player backend adapter abstraction and adapter lifecycle..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/adapter/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'player_adapter.dart';
export 'player_adapter_capabilities.dart';
export 'player_adapter_config.dart';
export 'player_adapter_context.dart';
export 'player_adapter_error.dart';
export 'player_adapter_event.dart';
export 'player_adapter_factory.dart';
export 'player_adapter_metrics.dart';
export 'player_adapter_registry.dart';
export 'player_adapter_selector.dart';
export 'player_adapter_state.dart';
