import 'performance_sample.dart';
import 'package:clock/clock.dart';

/// Collects and retains performance measurements for the media core.
///
/// A [PerformanceMonitor] provides lightweight timing utilities for
/// synchronous and asynchronous operations and keeps a bounded history of
/// [PerformanceSample] instances.
///
/// Responsibilities:
///
/// - measure synchronous operations
/// - measure asynchronous operations
/// - retain recent performance samples
/// - calculate basic aggregate timing information
/// - limit retained sample count
///
/// It does not:
///
/// - decide application-specific performance policy
/// - render performance information
/// - persist performance data
/// - emit player events
///
/// Those responsibilities belong to:
///
/// - DiagnosticsManager
/// - the caller consuming the samples
final class PerformanceMonitor {
  /// Creates a performance monitor.
  ///
  /// [maxSamples] controls the maximum number of samples retained in memory.
  PerformanceMonitor({this.maxSamples = 200}) : assert(maxSamples > 0);

  /// Maximum number of performance samples retained.
  final int maxSamples;

  /// Retained performance samples.
  final List<PerformanceSample> _samples = [];

  /// Whether this monitor has been disposed.
  bool _disposed = false;

  /// Current retained performance samples.
  ///
  /// The returned list cannot be modified by the caller.
  List<PerformanceSample> get samples {
    return List<PerformanceSample>.unmodifiable(_samples);
  }

  /// Number of retained performance samples.
  int get sampleCount {
    return _samples.length;
  }

  /// Duration of the most recently recorded sample.
  Duration? get lastDuration {
    if (_samples.isEmpty) {
      return null;
    }

    return _samples.last.duration;
  }

  /// Average duration of all retained samples.
  ///
  /// Returns `null` when there are no samples.
  Duration? get averageDuration {
    if (_samples.isEmpty) {
      return null;
    }

    final totalMicroseconds = _samples.fold<int>(0, (total, sample) => total + sample.duration.inMicroseconds);

    return Duration(microseconds: totalMicroseconds ~/ _samples.length);
  }

  /// Adds a performance sample.
  ///
  /// The timestamp is generated by the monitor using the package clock so
  /// that the measurement remains controllable in tests.
  void add(Duration duration, {String name = '', Map<String, Object?> metadata = const {}}) {
    _ensureNotDisposed();

    _samples.add(PerformanceSample(timestamp: clock.now(), duration: duration, name: name, metadata: metadata));

    _trim();
  }

  /// Measures a synchronous operation.
  ///
  /// The operation's elapsed time is automatically recorded even when
  /// [callback] throws.
  T measure<T>(String name, T Function() callback, {Map<String, Object?> metadata = const {}}) {
    _ensureNotDisposed();

    final stopwatch = Stopwatch()..start();

    try {
      return callback();
    } finally {
      stopwatch.stop();

      add(stopwatch.elapsed, name: name, metadata: metadata);
    }
  }

  /// Measures an asynchronous operation.
  ///
  /// The operation's elapsed time is automatically recorded even when
  /// [callback] completes with an error.
  Future<T> measureAsync<T>(
    String name,
    Future<T> Function() callback, {
    Map<String, Object?> metadata = const {},
  }) async {
    _ensureNotDisposed();

    final stopwatch = Stopwatch()..start();

    try {
      return await callback();
    } finally {
      stopwatch.stop();

      add(stopwatch.elapsed, name: name, metadata: metadata);
    }
  }

  /// Removes all retained performance samples.
  void clear() {
    _ensureNotDisposed();

    _samples.clear();
  }

  /// Disposes the performance monitor.
  ///
  /// Retained samples are released and no further measurements may be
  /// recorded after disposal.
  void dispose() {
    if (_disposed) {
      return;
    }

    _disposed = true;
    _samples.clear();
  }

  /// Removes the oldest samples when the retention limit is exceeded.
  void _trim() {
    final excess = _samples.length - maxSamples;

    if (excess <= 0) {
      return;
    }

    _samples.removeRange(0, excess);
  }

  /// Ensures the monitor has not been disposed.
  void _ensureNotDisposed() {
    if (_disposed) {
      throw StateError('PerformanceMonitor has been disposed.');
    }
  }
}
