// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `preload` module.
///
/// Media preloading, warm-up and preload scheduling..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/preload/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/preload/preload_context.dart';
export 'package:media_core/preload/preload_manager.dart';
export 'package:media_core/preload/preload_metrics.dart';
export 'package:media_core/preload/preload_priority.dart';
export 'package:media_core/preload/preload_request.dart';
export 'package:media_core/preload/preload_scheduler.dart';
export 'package:media_core/preload/preload_state.dart';
export 'package:media_core/preload/preload_task.dart';
