// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `cache` module.
///
/// Memory, disk and cache storage abstractions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/cache/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'cache_entry.dart';
export 'cache_eviction.dart';
export 'cache_key.dart';
export 'cache_manager.dart';
export 'cache_metrics.dart';
export 'cache_result.dart';
export 'cache_state.dart';
export 'cache_storage.dart';
export 'disk_cache.dart';
export 'memory_cache.dart';
