// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `cache` module.
///
/// Memory, disk and cache storage abstractions..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/cache/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/cache/cache_entry.dart';
export 'package:media_core/cache/cache_eviction.dart';
export 'package:media_core/cache/cache_key.dart';
export 'package:media_core/cache/cache_manager.dart';
export 'package:media_core/cache/cache_metrics.dart';
export 'package:media_core/cache/cache_result.dart';
export 'package:media_core/cache/cache_state.dart';
export 'package:media_core/cache/cache_storage.dart';
export 'package:media_core/cache/disk_cache.dart';
export 'package:media_core/cache/memory_cache.dart';
