// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `renderer` module.
///
/// PlayerIdentity rendering abstraction and rendering state..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/renderer/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/renderer/media_player_view.dart';
export 'package:media_core/renderer/player_overlay.dart';
export 'package:media_core/renderer/portable_player.dart';
export 'package:media_core/renderer/player_renderer.dart';
export 'package:media_core/renderer/player_surface.dart';
export 'package:media_core/renderer/player_view.dart';
export 'package:media_core/renderer/renderer_capabilities.dart';
export 'package:media_core/renderer/renderer_config.dart';
export 'package:media_core/renderer/renderer_controller.dart';
export 'package:media_core/renderer/renderer_state.dart';
export 'package:media_core/renderer/video_zoom_controller.dart';
