// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `renderer` module.
///
/// Player rendering abstraction and rendering state..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/renderer/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'player_overlay.dart';
export 'player_renderer.dart';
export 'player_surface.dart';
export 'player_view.dart';
export 'renderer_capabilities.dart';
export 'renderer_config.dart';
export 'renderer_controller.dart';
export 'renderer_state.dart';
