// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `casting` module.
///
/// Protocol-neutral casting: discovered render devices, the media
/// payload a receiver plays, transport state, and the controller that
/// turns a backend into UI state..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/casting/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/casting/cast_controller.dart';
export 'package:media_core/casting/cast_device.dart';
export 'package:media_core/casting/cast_media.dart';
export 'package:media_core/casting/cast_transport.dart';
export 'package:media_core/casting/media_cast_backend.dart';
