// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `coordinator` module.
///
/// Cross-module player and playback coordination..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/coordinator/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/coordinator/player_audio_coordinator.dart';
export 'package:media_core/coordinator/global_player_coordinator.dart';
export 'package:media_core/coordinator/lifecycle_coordinator.dart';
export 'package:media_core/coordinator/page_coordinator.dart';
export 'package:media_core/coordinator/playback_coordinator.dart';
export 'package:media_core/coordinator/player_coordinator.dart';
export 'package:media_core/coordinator/preload_coordinator.dart';
export 'package:media_core/coordinator/presentation_coordinator.dart';
export 'package:media_core/coordinator/resource_coordinator.dart';
