// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `coordinator` module.
///
/// Cross-module player and playback coordination..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/coordinator/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'player_audio_coordinator.dart';
export 'global_player_coordinator.dart';
export 'lifecycle_coordinator.dart';
export 'page_coordinator.dart';
export 'playback_coordinator.dart';
export 'player_coordinator.dart';
export 'preload_coordinator.dart';
export 'presentation_coordinator.dart';
export 'resource_coordinator.dart';
