// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `pool` module.
///
/// Player instance pooling, allocation and recycling..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/pool/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/pool/player_pool.dart';
export 'package:media_core/pool/pool_player_host.dart';
export 'package:media_core/pool/playback_pool_orchestrator.dart';
export 'package:media_core/pool/player_pool_allocator.dart';
export 'package:media_core/pool/player_pool_config.dart';
export 'package:media_core/pool/player_pool_manager.dart';
export 'package:media_core/pool/player_pool_metrics.dart';
export 'package:media_core/pool/player_pool_recycler.dart';
export 'package:media_core/pool/player_pool_snapshot.dart';
export 'package:media_core/pool/player_pool_state.dart';
