name: floating
description: Picture in Picture mode management for Flutter. Available only for Android.
version: 6.0.0
publish_to: none
resolution: workspace
homepage: https://github.com/wrbl606/floating
screenshots:
  - description: 'This screenshot shows the transformation from a full-screen application to a movable picture-in-picture form.'
    path: assets/cover.png
topics:
  - widgets
  - picture-in-picture
  - android
  - flutter

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.wroblewscy.marcin.floating.floating
        pluginClass: FloatingPlugin
