// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `policy` module.
///
/// Centralized cross-module player policies..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/policy/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/policy/audio_policy.dart';
export 'package:media_core/policy/cache_policy.dart';
export 'package:media_core/policy/concurrency_policy.dart';
export 'package:media_core/policy/fallback_policy.dart';
export 'package:media_core/policy/lifecycle_policy.dart';
export 'package:media_core/policy/memory_policy.dart';
export 'package:media_core/policy/playback_policy.dart';
export 'package:media_core/policy/player_policy.dart';
export 'package:media_core/policy/policy_context.dart';
export 'package:media_core/policy/preload_policy.dart';
export 'package:media_core/policy/presentation_policy.dart';
export 'package:media_core/policy/recovery_policy.dart';
export 'package:media_core/policy/resource_policy.dart';
export 'package:media_core/policy/thermal_policy.dart';
export 'package:media_core/policy/visibility_policy.dart';
