// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `policy` module.
///
/// Centralized cross-module player policies..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/policy/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'audio_policy.dart';
export 'cache_policy.dart';
export 'concurrency_policy.dart';
export 'fallback_policy.dart';
export 'lifecycle_policy.dart';
export 'memory_policy.dart';
export 'playback_policy.dart';
export 'player_policy.dart';
export 'policy_context.dart';
export 'preload_policy.dart';
export 'presentation_policy.dart';
export 'recovery_policy.dart';
export 'resource_policy.dart';
export 'thermal_policy.dart';
export 'visibility_policy.dart';
