// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `audio` module.
///
/// Audio focus, session, route, volume and mute management..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/audio/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/audio/audio_coordinator.dart';
export 'package:media_core/audio/audio_focus.dart';
export 'package:media_core/audio/audio_focus_state.dart';
export 'package:media_core/audio/audio_manager.dart';
export 'package:media_core/audio/audio_mute.dart';
export 'package:media_core/audio/audio_route.dart';
export 'package:media_core/audio/audio_session.dart';
export 'package:media_core/audio/audio_session_state.dart';
export 'package:media_core/audio/audio_volume.dart';
