// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `audio` module.
///
/// Audio focus, session, route, volume and mute management..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/audio/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'audio_coordinator.dart';
export 'audio_focus.dart';
export 'audio_focus_state.dart';
export 'audio_manager.dart';
export 'audio_mute.dart';
export 'audio_route.dart';
export 'audio_session.dart';
export 'audio_session_state.dart';
export 'audio_volume.dart';
