// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `source` module.
///
/// Media source abstraction, metadata, resolution and validation..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/source/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'flv/flv_legacy_hevc_relay.dart';
export 'flv/flv_legacy_hevc_rewriter.dart';
export 'flv/flv_tag_framer.dart';
export 'player_source.dart';
export 'source_descriptor.dart';
export 'source_format.dart';
export 'source_headers.dart';
export 'source_identity.dart';
export 'source_inspect_context.dart';
export 'source_inspector.dart';
export 'source_inspector_chain.dart';
export 'source_location.dart';
export 'source_media_type.dart';
export 'source_metadata.dart';
export 'source_protocol.dart';
export 'source_registry.dart';
export 'source_request.dart';
export 'source_resolve_context.dart';
export 'source_resolved.dart';
export 'source_resolver.dart';
export 'source_resolver_chain.dart';
export 'source_service.dart';
export 'source_type.dart';
export 'source_validator.dart';
