// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `source` module.
///
/// Media source abstraction, metadata, resolution and validation..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/source/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/source/flv/flv_legacy_hevc_relay.dart';
export 'package:media_core/source/flv/flv_legacy_hevc_rewriter.dart';
export 'package:media_core/source/flv/flv_tag_framer.dart';
export 'package:media_core/source/player_source.dart';
export 'package:media_core/source/source_descriptor.dart';
export 'package:media_core/source/source_format.dart';
export 'package:media_core/source/source_headers.dart';
export 'package:media_core/source/source_identity.dart';
export 'package:media_core/source/source_inspect_context.dart';
export 'package:media_core/source/source_inspector.dart';
export 'package:media_core/source/source_inspector_chain.dart';
export 'package:media_core/source/source_location.dart';
export 'package:media_core/source/source_media_type.dart';
export 'package:media_core/source/source_metadata.dart';
export 'package:media_core/source/source_protocol.dart';
export 'package:media_core/source/source_registry.dart';
export 'package:media_core/source/source_request.dart';
export 'package:media_core/source/source_resolve_context.dart';
export 'package:media_core/source/source_resolved.dart';
export 'package:media_core/source/source_resolver.dart';
export 'package:media_core/source/source_resolver_chain.dart';
export 'package:media_core/source/source_service.dart';
export 'package:media_core/source/source_type.dart';
export 'package:media_core/source/source_validator.dart';
