// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `identity` module.
///
/// Stable cross-module identity and identifier value objects..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/identity/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/identity/generation_id.dart';
export 'package:media_core/identity/identity_json_converters.dart';
export 'package:media_core/identity/operation_id.dart';
export 'package:media_core/identity/player_id.dart';
export 'package:media_core/identity/request_id.dart';
export 'package:media_core/identity/session_id.dart';
export 'package:media_core/identity/slot_id.dart';
export 'package:media_core/identity/source_id.dart';
