// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `composition` module.
///
/// Composition layer: the presentation timeline that aligns composite
/// tracks, plus schedule composition — programs, ad breaks and filler
/// placed onto one combined clock..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/composition/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/composition/composed_schedule.dart';
export 'package:media_core/composition/media_break.dart';
export 'package:media_core/composition/media_cue.dart';
export 'package:media_core/composition/media_segment.dart';
export 'package:media_core/composition/media_timeline.dart';
export 'package:media_core/composition/playback_schedule.dart';
export 'package:media_core/composition/schedule_clip.dart';
export 'package:media_core/composition/schedule_navigator.dart';
export 'package:media_core/composition/scheduled_playback.dart';
export 'package:media_core/composition/timeline_composer.dart';
export 'package:media_core/composition/timeline_track.dart';
