// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `task` module.
///
/// Task execution, scheduling, priority and cancellation..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/task/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'player_task.dart';
export 'task_cancel_token.dart';
export 'task_context.dart';
export 'task_id.dart';
export 'task_json_converters.dart';
export 'task_manager.dart';
export 'task_priority.dart';
export 'task_queue.dart';
export 'task_scheduler.dart';
export 'task_state.dart';
export 'task_type.dart';
