// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `task` module.
///
/// Task execution, scheduling, priority and cancellation..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/task/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/task/player_task.dart';
export 'package:media_core/task/task_cancel_token.dart';
export 'package:media_core/task/task_context.dart';
export 'package:media_core/task/task_errors.dart';
export 'package:media_core/task/task_id.dart';
export 'package:media_core/task/task_json_converters.dart';
export 'package:media_core/task/task_manager.dart';
export 'package:media_core/task/task_priority.dart';
export 'package:media_core/task/task_queue.dart';
export 'package:media_core/task/task_scheduler.dart';
export 'package:media_core/task/task_state.dart';
export 'package:media_core/task/task_type.dart';
