// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `error` module.
///
/// Error models, classification, formatting and error policies..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/error/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'error.dart';
export 'error_classifier.dart';
export 'error_context.dart';
export 'error_formatter.dart';
export 'error_policy.dart';
export 'error_utils.dart';
export 'player_error_category.dart';
export 'player_error_code.dart';
export 'player_exception.dart';
export 'player_failure.dart';
