// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `error` module.
///
/// Error models, classification, formatting and error policies..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/error/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/error/error.dart';
export 'package:media_core/error/error_classifier.dart';
export 'package:media_core/error/error_context.dart';
export 'package:media_core/error/error_formatter.dart';
export 'package:media_core/error/error_policy.dart';
export 'package:media_core/error/error_utils.dart';
export 'package:media_core/error/player_error_category.dart';
export 'package:media_core/error/player_error_code.dart';
export 'package:media_core/error/player_exception.dart';
export 'package:media_core/error/player_failure.dart';
