// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `session` module.
///
/// Player session lifecycle, context, state and operations..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/session/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/session/player_session.dart';
export 'package:media_core/session/session_context.dart';
export 'package:media_core/session/session_controller.dart';
export 'package:media_core/session/session_event.dart';
export 'package:media_core/session/session_generation.dart';
export 'package:media_core/session/session_lifecycle.dart';
export 'package:media_core/session/session_manager.dart';
export 'package:media_core/session/session_operation.dart';
export 'package:media_core/session/session_snapshot.dart';
export 'package:media_core/session/session_state.dart';
