// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `recording` module.
///
/// Recording abstraction, sessions, formats and backends..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/recording/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'recording_backend.dart';
export 'recording_config.dart';
export 'recording_error.dart';
export 'recording_format.dart';
export 'recording_manager.dart';
export 'recording_result.dart';
export 'recording_session.dart';
export 'recording_source.dart';
export 'recording_state.dart';
