// GENERATED MODULE LIBRARY - DO NOT EDIT.

/// Public library for the `recording` module.
///
/// Recording abstraction, sessions, formats and backends..
///
/// This library is generated automatically from the Dart files
/// physically contained in `lib/recording/`.
///
/// Do not edit this file manually.
/// Run the module library generation script again after adding,
/// removing or renaming files in this module.
library;

// ============================================================================
// Public exports
// ============================================================================

export 'package:media_core/recording/recording_backend.dart';
export 'package:media_core/recording/recording_config.dart';
export 'package:media_core/recording/recording_error.dart';
export 'package:media_core/recording/recording_format.dart';
export 'package:media_core/recording/recording_manager.dart';
export 'package:media_core/recording/recording_result.dart';
export 'package:media_core/recording/recording_session.dart';
export 'package:media_core/recording/recording_source.dart';
export 'package:media_core/recording/recording_state.dart';
